services:
  task_app:
    container_name: task_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://task_db:5432/GestorTareas
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=magic
    depends_on:
      - task_db
    working_dir: /app
    command: mvn spring-boot:run
  task_db:
    container_name: task_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: magic
      POSTGRES_DB: GestorTareas
  task_app_test:
    container_name: task_app_test
    image: maven:3.8.4-openjdk-17-slim
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - task_db
    command: mvn test