name: Run Maven Tests with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  maven-tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker Compose
      - name: Set up Docker Compose
        run: |
          docker compose up -d --build

      # Paso 3: Esperar a que los servicios estén listos
      - name: Wait for services to be ready
        run: |
          until docker compose exec db pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      # Paso 4: Ejecutar migraciones (opcional, si usas migraciones con Maven o SQL)
      - name: Run migrations
        run: |
          docker compose exec app mvn flyway:migrate

      # Paso 5: Ejecutar pruebas
      - name: Run tests
        run: |
          docker compose exec app mvn test

      # Paso 6: Simular despliegue
      - name: Simulate Deployment
        if: ${{ success() }}
        run: |
          echo "Deployment simulated: All tests passed!"
