name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: magic
          POSTGRES_DB: GestorTareas
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
          run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      

      - name: Build and Run Services
      run: docker-compose up --build -d

      - name: Wait for Services to be Healthy
          run: |
            echo "Waiting for services to be healthy..."
            docker-compose ps
            docker-compose logs
            sleep 20

      - name: Run tests
        run: docker-compose run --rm task_app_test

      - name: Simulate Deployment
          if: success()
          run: echo "🚀 TodoList App desplegada exitosamente"